version: '3'

services:
  
  gateway:
    build: gateway/.
    container_name: expa_gateway
    command: python app.py
    env_file: .env
    environment:
      DEBUG: 'true'
    ports:
      - "8001:8001"
